# Generated by Django 3.0.5 on 2021-11-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flour', models.IntegerField()),
                ('discount_flour', models.IntegerField()),
                ('after_discount_flour', models.IntegerField()),
                ('rice', models.IntegerField()),
                ('discount_rice', models.IntegerField()),
                ('after_discount_rice', models.IntegerField()),
                ('eggs', models.IntegerField()),
                ('discount_eggs', models.IntegerField()),
                ('after_discount_eggs', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('discount_sugar', models.IntegerField()),
                ('after_discount_sugar', models.IntegerField()),
                ('salt', models.IntegerField()),
                ('discount_salt', models.IntegerField()),
                ('after_discount_salt', models.IntegerField()),
                ('vegetables', models.IntegerField()),
                ('discount_vegetables', models.IntegerField()),
                ('after_discount_vegetables', models.IntegerField()),
            ],
        ),
    ]
