# Generated by Django 3.0.5 on 2021-11-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='pics')),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
